#!/usr/bin/env bash

set -xe

export PY_VERSION=${PY_VERSION-3.9}
export TF_DOCKER_BUILD_DEVEL_BRANCH=${TF_DOCKER_BUILD_DEVEL_BRANCH:-master}
export TF_DOCKER_BUILD_VERSION=${TF_DOCKER_BUILD_VERSION:-master}
export TF_BUILD_VERSION=${TF_BUILD_VERSION:-master}

export TF_DOCKER_BUILD_IMAGE_NAME=${TF_DOCKER_BUILD_IMAGE_NAME:-bitnami/intel-optimized-tensorflow}

export BUILD_AVX_CONTAINERS=${BUILD_AVX_CONTAINERS:-no}
export BUILD_AVX2_CONTAINERS=${BUILD_AVX2_CONTAINERS:-no}
export BUILD_SKX_CONTAINERS=${BUILD_SKX_CONTAINERS:-no}
export BUILD_CLX_CONTAINERS=${BUILD_CLX_CONTAINERS:-no}
export BUILD_ICX_CLIENT_CONTAINERS=${BUILD_ICX_CLIENT_CONTAINERS:-no}
export BUILD_ICX_SERVER_CONTAINERS=${BUILD_ICX_SERVER_CONTAINERS:-yes}

export TENSORFLOW_SRCS=${TENSORFLOW_SRCS:-tensorflow_srcs}
export TENSORFLOW_WHLS=${TENSORFLOW_WHLS:-tensorflow_whls}/${TF_BUILD_VERSION}/python${PY_VERSION}

mkdir -p ${TENSORFLOW_SRCS}
mkdir -p ${TENSORFLOW_WHLS}

set +xe
